### ISSUE TITLE
Add PrometheusDay Talk.

### ISSUE THREAD

**Issue by FlorianLautenschlager** [ChronixDB/chronixDB.github.io#24]

**Comment by FlorianLautenschlager** [comment]
Also the recording of the presentation held by @phxql

**Comment by FlorianLautenschlager** [comment]
http://www.slideshare.net/QAware/chronix-as-longterm-storage-for-prometheus

**Comment by phxql** [comment]
Video stream: https://www.youtube.com/watch?v=4fhXSgRmLHM&list=PLj6h78yzYM2PqgIGU1Qmi8nY7dqn9PCr4&index=62
